apiVersion: v1
kind: Service
metadata:
  name: microblog
  labels:
    app: microblog
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080  # external port
      protocol: TCP
      targetPort: 5000  # pod port
  selector:
    app: microblog  # match with Deployment's selectors.matchLabels.app
